export default {
  GO_GET: 'GO_GET',
  GO_GETACTIVECOLLECTION: 'GO_GETACTIVECOLLECTION',
  GO_SEARCH: 'GO_SEARCH',
  GO_UPDATECOLLECTION: 'GO_UPDATECOLLECTION',
  KEYBOARD_CLICKBUTTON: 'KEYBOARD_CLICKBUTTON',
  TIME: 'TIME',
  WEATHER: 'WEATHER',
  BANNER: 'BANNER'
};
